steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/my-gcp-website-464317/my-gcp-site', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'my-gcp-site',
      '--image', 'gcr.io/my-gcp-website-464317/my-gcp-site',
      '--region', 'asia-south1',
      '--allow-unauthenticated'
    ]
images:
  - 'gcr.io/my-gcp-website-464317/my-gcp-site'
options:
  logging: CLOUD_LOGGING_ONLY
